export const bankData = [
  {
    priority_bank: [
      { id: 1, name: "State Bank of India" },
      { id: 2, name: "Axis Bank Limited" },
      { id: 3, name: "Kotak Mahindra Bank Limited" },
      { id: 4, name: "Federal Bank Limited" }
    ],
    public_bank: [
      { id: 1, name: "Bank of Baroda" },
      { id: 2, name: "Bank of India" },
      { id: 3, name: "Bank of Maharashtra" },
      { id: 4, name: "Canara Bank" },
      { id: 5, name: "Central Bank of India" },
      { id: 6, name: "Indian Bank" },
      { id: 7, name: "Indian Overseas Bank" },
      { id: 8, name: "Punjab & Sind Bank" },
      { id: 9, name: "Punjab National Bank" },
      { id: 10, name: "UCO Bank" },
      { id: 11, name: "Union Bank of India" }
    ],
    domestic_private_bank: [
      { id: 1, name: "Bandhan Bank Limited" },
      { id: 2, name: "CSB Bank Limited" },
      { id: 3, name: "City Union Bank Limited" },
      { id: 4, name: "DCB Bank Limited" },
      { id: 5, name: "Dhanlaxmi Bank Limited" },
      { id: 6, name: "HDFC Bank Limited" },
      { id: 7, name: "ICICI Bank Limited" },
      { id: 8, name: "IndusInd Bank Limited" },
      { id: 9, name: "IDFC FIRST Bank Limited" },
      { id: 10, name: "Jammu & Kashmir Bank Limited" },
      { id: 11, name: "Karnataka Bank Limited" },
      { id: 12, name: "Karur Vysya Bank Limited" },
      { id: 13, name: "Nainital Bank Limited" },
      { id: 14, "name": "RBL Bank Limited" },
      { id: 15, "name": "South Indian Bank Limited" },
      { id: 16, "name": "Tamilnad Mercantile Bank Limited" },
      { id: 17, "name": "YES Bank Limited" },
      { id: 18, "name": "IDBI Bank Limited" }
    ],
    small_finance_bank: [
      { id: 1, name: "Au Small Finance Bank Limited" },
      { id: 2, name: "Capital Small Finance Bank Limited" },
      { id: 3, name: "Equitas Small Finance Bank Limited" },
      { id: 4, name: "ESAF Small Finance Bank Limited" },
      { id: 5, name: "Suryoday Small Finance Bank Limited" },
      { id: 6, name: "Ujjivan Small Finance Bank Limited" },
      { id: 7, name: "Utkarsh Small Finance Bank Limited" },
      { id: 8, name: "slice Small Finance Bank Limited" },
      { id: 9, name: "Jana Small Finance Bank Limited" },
      { id: 10, name: "Shivalik Small Finance Bank Limited" },
      { id: 11, name: "Unity Small Finance Bank Limited" }
    ],
    payments_bank: [
      { id: 1, name: "India Post Payments Bank Limited" },
      { id: 2, name: "Fino Payments Bank Limited" },
      { id: 3, name: "Paytm Payments Bank Limited" },
      { id: 4, name: "Airtel Payments Bank Limited" },
      { id: 5, name: "NSDL Payments Bank Limited" }
    ],
    regional_rural_bank: [
      { id: 1, name: "Andhra Pradesh Grameena Bank" },
      { id: 2, name: "Assam Gramin Bank" },
      { id: 3, name: "Arunachal Pradesh Rural Bank" },
      { id: 4, name: "Bihar Gramin Bank" },
      { id: 5, name: "Chhattisgarh Gramin Bank" },
      { id: 6, name: "Gujarat Gramin Bank" },
      { id: 7, name: "Haryana Gramin Bank" },
      { id: 8, name: "Himachal Pradesh Gramin Bank" },
      { id: 9, name: "Jharkhand Gramin Bank" },
      { id: 10, name: "Jammu and Kashmir Grameen Bank" },
      { id: 11, name: "Karnataka Grameena Bank" },
      { id: 12, name: "Kerala Grameena Bank" },
      { id: 13, name: "Maharashtra Gramin Bank" },
      { id: 14, name: "Madhya Pradesh Gramin Bank" },
      { id: 15, name: "Manipur Rural Bank" },
      { id: 16, name: "Meghalaya Rural Bank" },
      { id: 17, name: "Mizoram Rural Bank" },
      { id: 18, name: "Nagaland Rural Bank" },
      { id: 19, name: "Odisha Grameen Bank" },
      { id: 20, name: "Punjab Gramin Bank" },
      { id: 21, name: "Puducherry Grama Bank" },
      { id: 22, name: "Rajasthan Gramin Bank" },
      { id: 23, name: "Tamil Nadu Grama Bank" },
      { id: 24, name: "Telangana Grameena Bank" },
      { id: 25, name: "Tripura Gramin Bank" },
      { id: 26, name: "Uttar Pradesh Gramin Bank" },
      { id: 27, name: "Uttarakhand Gramin Bank" },
      { id: 28, name: "West Bengal Gramin Bank" }
    ],
    foreign_bank: [
      { id: 1, name: "AB Bank PLC" },
      { id: 2, name: "American Express Banking Corporation" },
      { id: 3, name: "Australia and New Zealand Banking Group Ltd." },
      { id: 4, name: "Barclays Bank Plc." },
      { id: 5, name: "Bank of America National Association" },
      { id: 6, name: "Bank of Bahrain and Kuwait B.S.C." },
      { id: 7, name: "Bank of Ceylon" },
      { id: 8, name: "Bank of China Limited" },
      { id: 9, name: "Bank of Nova Scotia" },
      { id: 10, name: "BNP Paribas" },
      { id: 11, name: "Citibank N.A." },
      { id: 12, name: "Cooperatieve Rabobank U.A." },
      { id: 13, name: "Credit Agricole Corporate and Investment Bank" },
      { id: 14, name: "CTBC Bank Co., Ltd." },
      { id: 15, name: "DBS Bank India Limited" },
      { id: 16, name: "Deutsche Bank A.G." },
      { id: 17, name: "Doha Bank Q.P.S.C" },
      { id: 18, name: "Emirates NBD Bank P.J.S.C" },
      { id: 19, name: "First Abu Dhabi Bank PJSC" },
      { id: 20, name: "FirstRand Bank Limited" },
      { id: 21, name: "Hong Kong and Shanghai Banking Corporation Limited" },
      { id: 22, name: "Industrial and Commercial Bank of China" },
      { id: 23, name: "Industrial Bank of Korea" },
      { id: 24, name: "J.P. Morgan Chase Bank N.A." },
      { id: 25, name: "JSC VTB Bank" },
      { id: 26, name: "KEB Hana Bank" },
      { id: 27, name: "Kookmin Bank" },
      { id: 28, name: "Mashreqbank P.S.C" },
      { id: 29, name: "Mizuho Bank Ltd." },
      { id: 30, name: "MUFG Bank, Ltd." },
      { id: 31, name: "NatWest Markets Plc" },
      { id: 32, name: "NongHyup Bank" },
      { id: 33, name: "PT Bank Maybank Indonesia TBK" },
      { id: 34, name: "Qatar National Bank (Q.P.S.C.)" },
      { id: 35, name: "Sberbank" },
      { id: 36, name: "SBM Bank (India) Limited" },
      { id: 37, name: "Shinhan Bank" },
      { id: 38, name: "Societe Generale" },
      { id: 39, name: "Sonali Bank PLC" },
      { id: 40, name: "Standard Chartered Bank" },
      { id: 41, name: "Sumitomo Mitsui Banking Corporation" },
      { id: 42, name: "United Overseas Bank Limited" },
      { id: 43, name: "UBS AG" },
      { id: 44, name: "Woori Bank" }
    ]
  }
];